name: CI
on: push

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.3
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: | 
          pnpm install

      - name: "Run tests"
        run: pnpm frontend:test

      - name: "Run lint"
        run: pnpm frontend:lint